feat!: Drop Support & Dependency on AWS SDK V2
aws/aws-encryption-sdk-javascript pull request #1177
Opened 2023-06-29 19:46 UTC by texastony

*Issue #, if available:* #1100, #922, #865

*Description of changes:* `Drop Support & Dependency on AWS SDK V2`

BREAKING CHANGE:
The AWS Encryption SDK for JavaScript:
- does not supports the AWS SDK for JavaScript V2
- requires the AWS SDK for JavaScript V3's kms-client (if using the KMS Keyring).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

# Check any applicable:
- [ ] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.

2023-06-29 21:06 UTC, texastony commented
All tests passed except for the [testVectorsBrowser](https://tiny.amazon.com/hmn3thb1/IsenLink).

That failed while trying to build `integration-browser`:
```
node:internal/modules/cjs/loader:1080
  throw err;

Error: Cannot find module '@aws-sdk/client-kms'
Require stack:
- /root/.npm/_npx/a05978ae8c8d6c1f/node_modules/@aws-crypto/kms-keyring-browser/build/main/src/kms_keyring_browser.js
- /root/.npm/_npx/a05978ae8c8d6c1f/node_modules/@aws-crypto/kms-keyring-browser/build/main/src/index.js
- /root/.npm/_npx/a05978ae8c8d6c1f/node_modules/@aws-crypto/client-browser/build/main/src/index.js
- /root/.npm/_npx/a05978ae8c8d6c1f/node_modules/@aws-crypto/integration-browser/build/main/src/cli.js
...
    at Object.<anonymous> (/root/.npm/_npx/a05978ae8c8d6c1f/node_modules/@aws-crypto/kms-keyring-browser/build/main/src/kms_keyring_browser.js:12:22)
...
  code: 'MODULE_NOT_FOUND',
...
```

So something is not configured to depend on the KMS Client correctly.

2023-06-30 01:03 UTC, ajewellamz approved these changes

2023-06-30 15:38 UTC, seebees commented on modules/kms-keyring-browser/test/kms_keyring_browser.test.ts
> -    'arn:aws:kms:us-west-2:658956600833:alias/EncryptDecrypt'
Just because we are changing the default, why are we removing the tests for the old SDK?

2023-06-30 15:38 UTC, seebees commented on modules/kms-keyring-browser/test/kms_mrk_discovery_keyring_browser.test.ts
> -import { KMS as V2KMS } from 'aws-sdk'
Same comment as above. Why does changing the default remove support? Or the need to test that support?

2023-06-30 15:39 UTC, seebees requested changes
Why are we not testing the SDK v2?
Until we remove support we should continue to test it

2023-06-30 17:06 UTC, texastony commented
> Why are we not testing the SDK v2? Until we remove support we should continue to test it

In this PR, I went all the way, and removed V2 support entirely. 
(Or at least I tried to.)

I take it that you object to to that. 

I will refactor this PR to return SDK V2 Support, but not take a dependency on it.

2023-07-02 00:22 UTC, texastony commented
Replaced by https://github.com/aws/aws-encryption-sdk-javascript/pull/1180

2023-07-02 00:22 UTC, closed without merging