chore: Add support policy
aws/aws-encryption-sdk-javascript pull request #644
Opened 2021-07-06 17:26 UTC by farleyb-amazon

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-07-06 19:28 UTC, texastony submitted a review, later dismissed

2021-07-07 23:07 UTC, seebees approved these changes

2021-07-12 20:45 UTC, seebees requested changes
Update release date

2021-07-12 20:45 UTC, seebees commented on SUPPORT_POLICY.rst
> +      - 2021-07-08
```suggestion
      - 2021-07-13
```

2021-07-12 20:45 UTC, seebees commented on SUPPORT_POLICY.rst
> +      - 2021-07-08
```suggestion
      - 2021-07-13
```

2021-07-12 20:46 UTC, seebees approved these changes

2021-07-12 20:59 UTC, merged